### ISSUE TITLE
`Error: ENOENT: no such file or directory, lstat '/proc/1/task/1/fdinfo/17'`

### ISSUE THREAD

**Issue by AliAlmasi** [devatherock/minify-js#26]
Error while trying to run the action for the first time. I'm not sure if the problem is caused by the `.yaml` file I created.

```
Run docker://devatherock/minify-js:3.1.0
  with:
    directory: /
    output: /mini/
    add_suffix: false
/usr/bin/docker run --name devatherockminifyjs310_ef6ac5 --label d6b8dc --workdir /github/workspace --rm -e "INPUT_DIRECTORY" -e "INPUT_OUTPUT" -e "INPUT_ADD_SUFFIX" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e 
node:internal/fs/utils:353
    throw err;
    ^
Error: ENOENT: no such file or directory, lstat '/proc/1/task/1/fdinfo/17'
    at Object.lstatSync (node:fs:1660:3)
    at isDirectory (file:///app/lib/utils.mjs:43:13)
    at minifyFiles (file:///app/lib/minify-js.mjs:46:7)
    at file:///app/lib/minify-js.mjs:52:9
    at Array.forEach (<anonymous>)
    at file:///app/lib/minify-js.mjs:51:13
    at FSReqCallback.oncomplete (node:fs:189:23) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/proc/1/task/1/fdinfo/17'
}
Node.js v20.10.0
```

[Full raw log is available here.](https://github.com/user-attachments/files/16145314/0_build.txt)

**Comment by AliAlmasi** [comment]
BTW, this is my `minify.yaml` file:

```
name: Minify CSS
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          directory: '/'
          output: '/mini/'
          add_suffix: false
#          inclusions: |-
#            .*assets.*
#            .*static/index.html
#          exclusions: |-
#            .*assets/generated/.*
```
