### ISSUE TITLE
Anyway to only target certain files for minifying?

### ISSUE THREAD

**Issue by t3pfaffe** [devatherock/minify-js#5]
Would like to be able to specify it only minifying certain files in my assets directory. Is this possible? Maybe as a filter built into the directory parameter since the action seems to just be using the find command?

**Comment by devatherock** [comment]
This should now be possible with a config like below:

```yaml
steps:
  - name: HTML/CSS/JS Minifier
    uses: docker://devatherock/minify-js:3.0.0
    with:
      directory: 'path/to/assets'
      inclusions: |-
        .*scripts.js.*
        .*static/index.html.*
```
